### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by ck-unifr** [lucidrains/toolformer-pytorch#8]
#### Description
After installing toolformer with "$ pip install toolformer-pytorch", I tried to run the example.
When I call "from toolformer_pytorch import Toolformer, PaLM", I have got a type error.

#### Screenshots
>>> import torch
>>> from toolformer_pytorch import Toolformer, PaLM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/memect/ck/workspace/toolformer-pytorch/toolformer_pytorch/__init__.py", line 3, in <module>
    from toolformer_pytorch.toolformer_pytorch import (
  File "/home/memect/ck/workspace/toolformer-pytorch/toolformer_pytorch/toolformer_pytorch.py", line 110, in <module>
    registry: dict[str, Callable],
TypeError: 'type' object is not subscriptable

**Comment by masfumy** [comment]
Which version of python interpreter are you using? I resolved the problem by updating from 3.8 to 3.9.  https://stackoverflow.com/questions/59101121/type-hint-for-a-dict-gives-typeerror-type-object-is-not-subscriptable

**Comment by ck-unifr** [comment]
> Which version of python interpreter are you using? I resolved the problem by updating from 3.8 to 3.9. https://stackoverflow.com/questions/59101121/type-hint-for-a-dict-gives-typeerror-type-object-is-not-subscriptable

Thanks. The version of python was 3.8.
